# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2faa9cb68e4b1436ab9f4ffe1bbdb71"
name = "admin-action-extension-app"
handle = "admin-action-extension-app-2"
application_url = "https://school-era-tablet-sciences.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_draft_orders"

[auth]
redirect_urls = [
  "https://school-era-tablet-sciences.trycloudflare.com/auth/callback",
  "https://school-era-tablet-sciences.trycloudflare.com/auth/shopify/callback",
  "https://school-era-tablet-sciences.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
